behaviors:
  Mouse:
    trainer_type: ppo
    hyperparameters:    
      batch_size: 2048
      buffer_size: 100000
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule:   linear
    network_settings:   
      normalize:    false
      hidden_units: 128
      num_layers:   2
      vis_encode_type:  simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints:   5
    checkpoint_interval:    500000
    max_steps:  15000000
    time_horizon:   64
    summary_freq:   20000
    threaded:   true
  Cat:
    trainer_type: ppo
    hyperparameters:    
      batch_size: 1240
      buffer_size: 100000
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule:   linear
    network_settings:   
      normalize:    false
      hidden_units: 128
      num_layers:   2
      vis_encode_type:  simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints:   5
    checkpoint_interval:    500000
    max_steps:  15000000
    time_horizon:   64
    summary_freq:   20000
    threaded:   true